### ISSUE TITLE
[Feature request] Blacklist/Whitelist of advancements

### ISSUE THREAD

**Issue by ghost** [Lomeli12/TrophySlots#23]
Hi!
Your mod is an incredible find for me.

But it should be great to add a new list in config, in which advancements ids can be added. So only advancements that are in this list unlock new slots for player. 

And also add a new boolean "Blacklist", that inverts previous list functionality when is set to true, so advancement that are in list won't unlock new slots for player.

And... it would be great to make a command that will print all advancements ids and their names in chat or a certain file, so people can save their time seeking for advancement id from another mod etc.

It's not very useful for common players, but it could be an amazing feature for modpack creators and others who make a playable content for minecraft.

**Comment by Lomeli12** [comment]
I could've sworn I already had an advancement whitelist feature, but I guess at some point I completely forgot to add it back in. That command does sound useful, and I'm thinking about printing them to a file instead so that you don't need to have the game open and have a tiny text window to scroll through the advancement IDs.

**Comment by ghost** [comment]
That sounds great! And yes, printing anything to a file is much more convenient (I'm using CraftTweaker, so I have my ct.log opened all the time, and it's much better when u can seek for a row with ur text editor etc rather than scroll all the chat in the game).
Thank you for such response!
